/*******************************************************************************
 * Service，重新生成不会覆盖
 *
 * Service For OAuthUser
 * Auto Generated by CokGen At 2016-01-21 10:40:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.oauth.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cokapp.quick.module.oauth.core.OAuthTypeEnum;
import com.cokapp.quick.module.oauth.entity.OAuthUser;
import com.cokapp.quick.module.oauth_gen.service.OAuthUserServiceGen;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
@Service
@Transactional
public class OAuthUserService extends OAuthUserServiceGen {

	public OAuthUser findByOAuthTypeAndOAuthId(OAuthTypeEnum oAuthType, String oAuthId) {
		return this.getDao().findByOAuthTypeAndOAuthId(oAuthType, oAuthId);
	}

}
