/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * API For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package ${meta.getPackageName()}.web.api;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import ${meta.getPackageName()}_gen.web.api.${meta.getClassName()}APIGen;

@Controller
@RequestMapping(value = { "/api/${meta.getClassName()?lower_case}" })
public class ${meta.getClassName()}API extends ${meta.getClassName()}APIGen {

}




