/*******************************************************************************
 * 在此扩展Dao，重新生成不会覆盖
 * 在此添加的接口方法，需要实现类支持
 * 
 * Dao For Cliphistory
 * Auto Generated by CokGen At 2015-10-16 10:55:28
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie.dao.extend;

public interface CliphistoryDaoExtend {

}
