/*******************************************************************************
 * Dao，重新生成会覆盖，不要修改此类
 * 
 * Dao For ClipSubscribe
 * Auto Generated by CokGen At 2016-01-19 16:20:17
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie_gen.dao;

import org.springframework.stereotype.Repository;

import com.cokapp.tongbutie.entity.ClipSubscribe;
import com.cokapp.quick.core.orm.jpa.BaseDao;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午5:20:25
 */
@Repository
public interface ClipSubscribeDaoGen extends BaseDao<ClipSubscribe, Long> {

}






