/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * API For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package ${meta.getPackageName()}_gen.web.api;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import ${meta.getPackageName()}.entity.${meta.getClassName()};
import ${meta.getPackageName()}.service.${meta.getClassName()}Service;
import com.cokapp.quick.core.service.BaseService;
import com.cokapp.quick.core.web.controller.BaseController;
import com.cokapp.quick.core.web.view.JsonResult;

public abstract class ${meta.getClassName()}APIGen extends BaseController<${meta.getClassName()}, ${meta.getIdTypeName()}> {

	@Autowired
	private ${meta.getClassName()}Service svr;

	@RequestMapping(value = { "" }, method = { RequestMethod.POST })
	@ResponseBody
	public JsonResult<${meta.getClassName()}> create(@RequestBody ${meta.getClassName()} entity) {
		this.getService().save(entity);
		return JsonResult.newSuccess(entity, "新建成功！");
	}

	@RequestMapping(value = "/{id}", method = { RequestMethod.DELETE })
	@ResponseBody
	public JsonResult<${meta.getClassName()}> delete(@PathVariable("id") ${meta.getIdTypeName()} id) {
		this.getService().delete(id);
		return JsonResult.<${meta.getClassName()}> newSuccess("删除成功！");
	}

	@Override
	protected BaseService<${meta.getClassName()}, ${meta.getIdTypeName()}> getBaseService() {
		return this.svr;
	}

	protected ${meta.getClassName()}Service getService() {
		return this.svr;
	}
	
	@RequestMapping(value = { "" }, method = { RequestMethod.GET })
	@ResponseBody
	public JsonResult<${meta.getClassName()}> list(HttpServletRequest request,
			@RequestParam(value = "paged", required = false, defaultValue = "false") Boolean paged) {
		JsonResult<${meta.getClassName()}> json = JsonResult.newSuccess();
		if (paged) {
			json.setData(this.findPage(request));
		} else {
			json.setData(this.findList(request));
		}
		return json;
	}
	
	@RequestMapping(value = { "/{id}" }, method = { RequestMethod.POST })
	@ResponseBody
	public JsonResult<${meta.getClassName()}> update(@RequestBody ${meta.getClassName()} entity, @PathVariable("id") ${meta.getIdTypeName()} id) {
		entity.setId(id);
		this.getService().update(entity);
		return JsonResult.newSuccess(entity);
	}

	@RequestMapping(value = { "/{id}" }, method = { RequestMethod.GET }, produces = "application/json")
	@ResponseBody
	public JsonResult<${meta.getClassName()}> view(@PathVariable("id") ${meta.getIdTypeName()} id) {
		${meta.getClassName()} entity = this.getService().findOne(id);
		if (entity == null) {
			return JsonResult.newError("没有找到ID(%s)对应的记录！", id);
		}		
		return JsonResult.newSuccess(entity);
	}

}





