/*******************************************************************************
 * DaoExtend实现类，重新生成不会覆盖
 *
 * Dao For Privilege
 * Auto Generated by CokGen At 2015-10-16 15:50:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.auth.dao.extend.impl;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

import com.cokapp.quick.module.auth.dao.extend.PrivilegeDaoExtend;
import com.cokapp.quick.module.auth.entity.Privilege;

public class PrivilegeDaoImpl implements PrivilegeDaoExtend {
	@PersistenceContext
	private EntityManager entityManager;

	@Override
	public List<Privilege> findByUserId(Long userid) {
		String sql = "select p.* from" + " auth_privilege p," + " auth_role_privilege rp," + " auth_user_role ur"
				+ " where ur.user_id=:userid" + " and ur.role_id=rp.role_id" + " and rp.privilege_id=p.id";

		TypedQuery<Privilege> query = this.entityManager.createNamedQuery(sql, Privilege.class);
		query.setParameter("userid", userid);

		return query.getResultList();
	}
}