/*******************************************************************************
 * DaoExtend实现类，重新生成不会覆盖
 * 
 * Dao For Role
 * Auto Generated by CokGen At 2015-10-16 15:50:46
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.auth.dao.extend.impl;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import com.cokapp.quick.module.auth.dao.extend.RoleDaoExtend;

public class RoleDaoImpl implements RoleDaoExtend{
	@PersistenceContext
	private EntityManager entityManager;
}