/*******************************************************************************
 * DaoExtend实现类，重新生成不会覆盖
 * 
 * Dao For UserRegister
 * Auto Generated by CokGen At 2016-03-14 17:37:25
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.auth.dao.extend.impl;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import com.cokapp.quick.module.auth.dao.extend.UserRegisterDaoExtend;

public class UserRegisterDaoImpl implements UserRegisterDaoExtend{
	@PersistenceContext
	private EntityManager entityManager;
}