/*******************************************************************************
 * Dao，重新生成会覆盖，不要修改此类
 * 
 * Dao For Role
 * Auto Generated by CokGen At 2016-03-14 17:37:26
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth_gen.dao;

import org.springframework.stereotype.Repository;

import com.cokapp.quick.module.auth.entity.Role;
import com.cokapp.quick.core.orm.jpa.BaseDao;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午5:20:25
 */
@Repository
public interface RoleDaoGen extends BaseDao<Role, Long> {

}






