/*******************************************************************************
 * Dao，重新生成不会覆盖
 * 
 * Dao For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package ${meta.getPackageName()}.dao;

import java.util.Set;

import org.springframework.stereotype.Repository;

import ${meta.getPackageName()}.dao.extend.${meta.getClassName()}DaoExtend;
import ${meta.getPackageName()}.entity.${meta.getClassName()};
import ${meta.getPackageName()}_gen.dao.${meta.getClassName()}DaoGen;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午3:32:10
 */
@Repository
public interface ${meta.getClassName()}Dao extends ${meta.getClassName()}DaoGen, ${meta.getClassName()}DaoExtend {
	Set<${meta.getClassName()}> findByIdIn(${meta.getIdTypeName()}... ids);
}







