/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * API For Privilege
 * Auto Generated by CokGen At 2015-10-16 15:50:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth.web.api;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.cokapp.quick.module.auth_gen.web.api.PrivilegeAPIGen;

@Controller
@RequestMapping(value = { "/api/privilege" })
public class PrivilegeAPI extends PrivilegeAPIGen {

}




