/*******************************************************************************
 * Dao，重新生成会覆盖，不要修改此类
 * 
 * Dao For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package ${meta.getPackageName()}_gen.dao;

import org.springframework.stereotype.Repository;

import ${meta.getPackageName()}.entity.${meta.getClassName()};
import com.cokapp.quick.core.orm.jpa.BaseDao;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午5:20:25
 */
@Repository
public interface ${meta.getClassName()}DaoGen extends BaseDao<${meta.getClassName()}, ${meta.getIdTypeName()}> {

}






