/*******************************************************************************
 * DaoExtend实现类，重新生成不会覆盖
 * 
 * Dao For OAuthUser
 * Auto Generated by CokGen At 2016-01-21 10:40:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.oauth.dao.extend.impl;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import com.cokapp.quick.module.oauth.dao.extend.OAuthUserDaoExtend;

public class OAuthUserDaoImpl implements OAuthUserDaoExtend{
	@PersistenceContext
	private EntityManager entityManager;
}