/*******************************************************************************
 * Service，重新生成不会覆盖
 *
 * Service For User
 * Auto Generated by CokGen At 2015-10-16 15:50:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.auth.service;

import org.junit.Assert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.Rollback;
import org.springframework.transaction.annotation.Transactional;

import com.cokapp.quick.BaseSpringTest;
import com.cokapp.quick.module.auth.entity.User;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
public class UserServiceTest extends BaseSpringTest {

	@Autowired
	private UserService userService;

	// @Test
	@Transactional
	@Rollback(false)
	public void testGenWeixinUser() {
		User newUser = this.userService.genWeixinUser("dddddd");
		Assert.assertNotNull(newUser);
	}
}
