/*******************************************************************************
 * Service，重新生成会覆盖，不要修改此类
 * 
 * Service For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package ${meta.getPackageName()}_gen.service;

import org.springframework.beans.factory.annotation.Autowired;

import ${meta.getPackageName()}.dao.${meta.getClassName()}Dao;
import ${meta.getPackageName()}.entity.${meta.getClassName()};
import com.cokapp.quick.core.service.BaseService;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:23
 */
public abstract class ${meta.getClassName()}ServiceGen extends BaseService<${meta.getClassName()}, ${meta.getIdTypeName()}> {

	private ${meta.getClassName()}Dao dao;

	public ${meta.getClassName()}Dao getDao() {
		return this.dao;
	}

	@Autowired
	protected void set${meta.getClassName()}Dao(${meta.getClassName()}Dao dao) {
		this.baseDao = dao;
		this.dao = dao;
	}
}






