/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * API For ClipSubscribe
 * Auto Generated by CokGen At 2015-11-10 16:16:55
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie.web.api;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.cokapp.tongbutie_gen.web.api.ClipSubscribeAPIGen;

@Controller
@RequestMapping(value = { "/api/clipsubscribe" })
public class ClipSubscribeAPI extends ClipSubscribeAPIGen {

}




