/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * API For Cliphistory
 * Auto Generated by CokGen At 2015-10-16 10:55:28
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie.web.api;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.cokapp.tongbutie_gen.web.api.CliphistoryAPIGen;

@Controller
@RequestMapping(value = { "/api/cliphistory" })
public class CliphistoryAPI extends CliphistoryAPIGen {

}




