/*******************************************************************************
 * Service，重新生成会覆盖，不要修改此类
 * 
 * Service For OAuthUser
 * Auto Generated by CokGen At 2016-01-21 10:40:48
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.oauth_gen.service;

import org.springframework.beans.factory.annotation.Autowired;

import com.cokapp.quick.module.oauth.dao.OAuthUserDao;
import com.cokapp.quick.module.oauth.entity.OAuthUser;
import com.cokapp.quick.core.service.BaseService;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:23
 */
public abstract class OAuthUserServiceGen extends BaseService<OAuthUser, Long> {

	private OAuthUserDao dao;

	public OAuthUserDao getDao() {
		return this.dao;
	}

	@Autowired
	protected void setOAuthUserDao(OAuthUserDao dao) {
		this.baseDao = dao;
		this.dao = dao;
	}
}






