/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * Service For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package ${meta.getPackageName()}.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ${meta.getPackageName()}_gen.service.${meta.getClassName()}ServiceGen;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
@Service
@Transactional
public class ${meta.getClassName()}Service extends ${meta.getClassName()}ServiceGen {

}





