/*******************************************************************************
 * Service，重新生成不会覆盖
 *
 * Service For Role
 * Auto Generated by CokGen At 2015-10-16 15:50:46
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.auth.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cokapp.quick.module.auth_gen.service.RoleServiceGen;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
@Service
@Transactional
public class RoleService extends RoleServiceGen {

}
