/*******************************************************************************
 * Service，重新生成不会覆盖
 *
 * Service For UserRegister
 * Auto Generated by CokGen At 2016-03-14 17:37:25
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.quick.module.auth.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cokapp.quick.module.auth.entity.UserRegister;
import com.cokapp.quick.module.auth_gen.service.UserRegisterServiceGen;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
@Service
@Transactional
public class UserRegisterService extends UserRegisterServiceGen {

	public UserRegister findByEmail(String email) {
		return this.getDao().findByEmailAndDel(email, false);
	}

	public UserRegister findByHash(String hash) {
		return this.getDao().findByHashAndDel(hash, false);
	}

}
