/*******************************************************************************
 * 在此扩展Dao，重新生成不会覆盖
 * 在此添加的接口方法，需要实现类支持
 * 
 * Dao For OAuthUser
 * Auto Generated by CokGen At 2016-01-21 10:40:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.oauth.dao.extend;

public interface OAuthUserDaoExtend {

}
