/*******************************************************************************
 * 在此扩展Dao，重新生成不会覆盖
 * 在此添加的接口方法，需要实现类支持
 *
 * Dao For Privilege
 * Auto Generated by CokGen At 2015-10-16 15:50:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth.dao.extend;

import java.util.List;

import com.cokapp.quick.module.auth.entity.Privilege;

public interface PrivilegeDaoExtend {
	public List<Privilege> findByUserId(Long userid);
}
