/*******************************************************************************
 * 在此扩展Dao，重新生成不会覆盖
 * 在此添加的接口方法，需要实现类支持
 * 
 * Dao For UserRegister
 * Auto Generated by CokGen At 2016-03-14 17:37:25
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth.dao.extend;

public interface UserRegisterDaoExtend {

}
