/*******************************************************************************
 * Dao，重新生成会覆盖，不要修改此类
 * 
 * Dao For OAuthUser
 * Auto Generated by CokGen At 2016-01-21 10:40:48
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.oauth_gen.dao;

import org.springframework.stereotype.Repository;

import com.cokapp.quick.module.oauth.entity.OAuthUser;
import com.cokapp.quick.core.orm.jpa.BaseDao;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午5:20:25
 */
@Repository
public interface OAuthUserDaoGen extends BaseDao<OAuthUser, Long> {

}






