/*******************************************************************************
 * Service，重新生成不会覆盖
 *
 * Service For ClipSubscribe
 * Auto Generated by CokGen At 2015-11-10 16:21:38
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.tongbutie.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cokapp.tongbutie.entity.ClipSubscribe;
import com.cokapp.tongbutie_gen.service.ClipSubscribeServiceGen;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
@Service
@Transactional
public class ClipSubscribeService extends ClipSubscribeServiceGen {

	public ClipSubscribe findByClipboardAndUser(long clipboard, long user) {
		return this.getDao().findByClipboardAndUser(clipboard, user);
	}
}
