/*******************************************************************************
 * Service，重新生成不会覆盖
 *
 * Service For Cliphistory
 * Auto Generated by CokGen At 2015-10-16 10:55:28
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.tongbutie.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cokapp.tongbutie_gen.service.CliphistoryServiceGen;

/**
 *
 * @author dev@cokapp.com
 * @date 2015年8月31日 上午11:53:13
 */
@Service
@Transactional
public class CliphistoryService extends CliphistoryServiceGen {

}
