/*******************************************************************************
 * DaoExtend实现类，重新生成不会覆盖
 * 
 * Dao For Clipboard
 * Auto Generated by CokGen At 2015-10-16 10:55:28
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/

package com.cokapp.tongbutie.dao.extend.impl;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import com.cokapp.tongbutie.dao.extend.ClipboardDaoExtend;

public class ClipboardDaoImpl implements ClipboardDaoExtend{
	@PersistenceContext
	private EntityManager entityManager;
}