/*******************************************************************************
 * 在此扩展Dao，重新生成不会覆盖
 * 在此添加的接口方法，需要实现类支持
 * 
 * Dao For ${meta.getClassName()}
 * Auto Generated by CokGen At ${date.toString("YYYY-MM-dd HH:mm:ss")}
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package ${meta.getPackageName()}.dao.extend;

public interface ${meta.getClassName()}DaoExtend {

}
