/*******************************************************************************
 * Service，重新生成不会覆盖
 * 
 * API For Cliphistory
 * Auto Generated by CokGen At 2016-01-19 16:20:18
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie_gen.web.api;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.cokapp.tongbutie.entity.Cliphistory;
import com.cokapp.tongbutie.service.CliphistoryService;
import com.cokapp.quick.core.service.BaseService;
import com.cokapp.quick.core.web.controller.BaseController;
import com.cokapp.quick.core.web.view.JsonResult;

public abstract class CliphistoryAPIGen extends BaseController<Cliphistory, Long> {

	@Autowired
	private CliphistoryService svr;

	@RequestMapping(value = { "" }, method = { RequestMethod.POST })
	@ResponseBody
	public JsonResult<Cliphistory> create(@RequestBody Cliphistory entity) {
		this.getService().save(entity);
		return JsonResult.newSuccess(entity, "新建成功！");
	}

	@RequestMapping(value = "/{id}", method = { RequestMethod.DELETE })
	@ResponseBody
	public JsonResult<Cliphistory> delete(@PathVariable("id") Long id) {
		this.getService().delete(id);
		return JsonResult.<Cliphistory> newSuccess("删除成功！");
	}

	@Override
	protected BaseService<Cliphistory, Long> getBaseService() {
		return this.svr;
	}

	protected CliphistoryService getService() {
		return this.svr;
	}
	
	@RequestMapping(value = { "" }, method = { RequestMethod.GET })
	@ResponseBody
	public JsonResult<Cliphistory> list(HttpServletRequest request,
			@RequestParam(value = "paged", required = false, defaultValue = "false") Boolean paged) {
		JsonResult<Cliphistory> json = JsonResult.newSuccess();
		if (paged) {
			json.setData(this.findPage(request));
		} else {
			json.setData(this.findList(request));
		}
		return json;
	}
	
	@RequestMapping(value = { "/{id}" }, method = { RequestMethod.POST })
	@ResponseBody
	public JsonResult<Cliphistory> update(@RequestBody Cliphistory entity, @PathVariable("id") Long id) {
		entity.setId(id);
		this.getService().update(entity);
		return JsonResult.newSuccess(entity);
	}

	@RequestMapping(value = { "/{id}" }, method = { RequestMethod.GET }, produces = "application/json")
	@ResponseBody
	public JsonResult<Cliphistory> view(@PathVariable("id") Long id) {
		Cliphistory entity = this.getService().findOne(id);
		if (entity == null) {
			return JsonResult.newError("没有找到ID(%s)对应的记录！", id);
		}		
		return JsonResult.newSuccess(entity);
	}

}





