/*******************************************************************************
 * Dao，重新生成不会覆盖
 * 
 * Dao For Cliphistory
 * Auto Generated by CokGen At 2015-10-16 10:55:28
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie.dao;

import java.util.Set;

import org.springframework.stereotype.Repository;

import com.cokapp.tongbutie.dao.extend.CliphistoryDaoExtend;
import com.cokapp.tongbutie.entity.Cliphistory;
import com.cokapp.tongbutie_gen.dao.CliphistoryDaoGen;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午3:32:10
 */
@Repository
public interface CliphistoryDao extends CliphistoryDaoGen, CliphistoryDaoExtend {
	Set<Cliphistory> findByIdIn(Long... ids);
}







