/*******************************************************************************
 * Dao，重新生成不会覆盖
 *
 * Dao For ClipSubscribe
 * Auto Generated by CokGen At 2015-11-10 16:16:55
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.tongbutie.dao;

import java.util.Set;

import org.springframework.stereotype.Repository;

import com.cokapp.tongbutie.dao.extend.ClipSubscribeDaoExtend;
import com.cokapp.tongbutie.entity.ClipSubscribe;
import com.cokapp.tongbutie_gen.dao.ClipSubscribeDaoGen;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午3:32:10
 */
@Repository
public interface ClipSubscribeDao extends ClipSubscribeDaoGen, ClipSubscribeDaoExtend {
	ClipSubscribe findByClipboardAndUser(long clipboard, long user);

	Set<ClipSubscribe> findByIdIn(Long... ids);
}
