/*******************************************************************************
 * Dao，重新生成不会覆盖
 * 
 * Dao For Privilege
 * Auto Generated by CokGen At 2015-10-16 15:50:47
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth.dao;

import java.util.Set;

import org.springframework.stereotype.Repository;

import com.cokapp.quick.module.auth.dao.extend.PrivilegeDaoExtend;
import com.cokapp.quick.module.auth.entity.Privilege;
import com.cokapp.quick.module.auth_gen.dao.PrivilegeDaoGen;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午3:32:10
 */
@Repository
public interface PrivilegeDao extends PrivilegeDaoGen, PrivilegeDaoExtend {
	Set<Privilege> findByIdIn(Long... ids);
}







