/*******************************************************************************
 * Dao，重新生成不会覆盖
 * 
 * Dao For Role
 * Auto Generated by CokGen At 2015-10-16 15:50:46
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth.dao;

import java.util.Set;

import org.springframework.stereotype.Repository;

import com.cokapp.quick.module.auth.dao.extend.RoleDaoExtend;
import com.cokapp.quick.module.auth.entity.Role;
import com.cokapp.quick.module.auth_gen.dao.RoleDaoGen;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午3:32:10
 */
@Repository
public interface RoleDao extends RoleDaoGen, RoleDaoExtend {
	Set<Role> findByIdIn(Long... ids);
}







