/*******************************************************************************
 * Dao，重新生成不会覆盖
 *
 * Dao For UserRegister
 * Auto Generated by CokGen At 2016-03-14 17:37:25
 *
 * Copyright (c) cokapp.com
 * Email: dev@cokapp.com
 *******************************************************************************/
package com.cokapp.quick.module.auth.dao;

import java.util.Set;

import org.springframework.stereotype.Repository;

import com.cokapp.quick.module.auth.dao.extend.UserRegisterDaoExtend;
import com.cokapp.quick.module.auth.entity.UserRegister;
import com.cokapp.quick.module.auth_gen.dao.UserRegisterDaoGen;

/**
 *
 * @author heichengliang@talkweb.com.cn
 * @date 2015年8月27日 下午3:32:10
 */
@Repository
public interface UserRegisterDao extends UserRegisterDaoGen, UserRegisterDaoExtend {
	UserRegister findByEmailAndDel(String email, Boolean del);

	UserRegister findByHashAndDel(String hash, Boolean del);

	Set<UserRegister> findByIdIn(Long... ids);

}
